export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_SELECTED_DEVICE_TYPE = "SET_SELECTED_DEVICE_TYPE";
export const SET_SELECTED_CLASSIFICATION = "SET_SELECTED_CLASSIFICATION";
export const SET_SELECTED_MODEL = "SET_SELECTED_MODEL";
export const SET_SELECTED_COLOR= "SET_SELECTED_COLOR";
export const SET_SELECTED_ISSUE= "SET_SELECTED_ISSUE";
export const SET_SELECTED_DETAILS= "SET_SELECTED_DETAILS";
export const SET_SELECTED_SUMMARY= "SET_SELECTED_SUMMARY";
export const SET_SELECTED_SCHEDULE= "SET_SELECTED_SCHEDULE";


export const SET_SELECTED_CIENT_DETAILS= "SET_SELECTED__CIENT_DETAILS";